### PR TITLE
Make a TOC

### PR DESCRIPTION
**Pull request by steveklabnik**
Here's an initial draft of a table of contents for the book.

Thoughts?

### CODE REVIEW

**Comment by varjmes** [comment]
I'm certainly wanting to learn about these things. Does filesystems mean I/O?

**Comment by rylev** [comment]
All the topics sounds really great, but I'm curious as to what we will actually cover in them. It seems the topics could be wildly different in terms of depth and length needed to explain them than the previous chapters. To my unexperienced eyes, for example, the idea of "paging" which I assume will cover virtual memory topics could be a whole book. When compared to "A simple VGA driver", the scope seems very different. Is it possible that these new additions represent "sections" rather than chapters and that what is already written belongs to a "Getting started" or "Bootstrapping" section?

**Comment by steveklabnik** [comment]
> I'm certainly wanting to learn about these things. Does filesystems mean I/O?

It means being able to load stuff of of a drive. It will probably just be FAT32 or a very simple kind of file system. I'll explain more in the next comment...

>  It seems the topics could be wildly different in terms of depth and length needed to explain them than the previous chapters. 

The intention is to show off the basics of one approach. You're absolutely right that paging could be its own whole thing; for the purposes of this book, I would just want to get a basic page table going.

By showing an example of _one kind_ of these things, we can have a base that others can experiment from. Once this project is finished, you could try to replace just one part; imagine you're interested in scheduling. You could take everything else and just replace the scheduler. You could implement a different filesystem. Whatever :)

> Is it possible that these new additions represent "sections" rather than chapters

I guess I'm not sure what the distinction is between the two terms. These are just top-level items to be filled out, just like the 'long mode' bit was just filled out. 

I came up with this by starting from the end: what do we need to be running two user-mode programs at the same time. Well, to do that you need a scheduler, you need user mode, you need to be able to load the programs off of disk. Etc.

**Comment by rylev** [comment]
My distinction between sections and chapters is that sections are groupings of chapters with a common theme. If this were a book on cooking, you could imagine a section on desserts which contains chapters like "double fudge brownie" and "New York style cheesecake". 

When I read the items in the proposed TOC I see them more as thematic elements rather than recipes. Whereas the items written about so far have been more like recipes. "How do we get into long mode" is a different question from "how do we create a file system". The first can be answered by "please follow these steps". The second can only be answered with "first, we must define what we mean by a file system and define the components we want to build that get us there."

Does that make sense?

**Comment by steveklabnik** [comment]
Ah yeah. So I guess it's really an issue of _naming_ the chapters, I still see these all as recipes.

**Comment by rylev** [comment]
Great! Then perhaps we rename the chapters to make it clear that we're only dipping our toes in and trying to build the simplest version of X.

**Comment by steveklabnik** [comment]
Agreed. Any thoughts?

**Comment by rylev** [comment]
Having repetitive titles could be fun if they don't become too annoying:

"A simple VGA driver"
"A simple filesystem"
"A simple virtual memory system"
etc.

Not sure how that would end up working out.

**Comment by steveklabnik** [comment]
Yeah, that's my fear too. Hm.

**Comment by varjmes** [comment]
To chime in: I'd avoid "simple" :+1:

**Comment by rylev** [comment]
@steveklabnik as long as we keep in mind that the names of the chapters may give the wrong impression of the direction of the book if read incorrectly, I say we can merge this. Or would you want to give another try at rewriting the chapter names?

**Comment by steveklabnik** [comment]
Let's give it another few days, and if I don't get it done, let's just merge as-is for now.

**Comment by steveklabnik** [comment]
Merging as-is :)

**Pull request merged**
