### PR TITLE
Source control with git

### PR DESCRIPTION
**Pull request by steveklabnik**
Just a short note about git. This is all we _really_ need to say, though we could say more.

@dvberkel , you were interested in this before. Care to turn this into a little tutorial? Should this maybe be an Appendix instead? It feels like maybe it's not quite involved enough to justify a chapter here...

### CODE REVIEW

**Comment by varjmes** [comment]
A lot of folk are visual learners so here are some great git interactive tutorials:

https://try.github.io for a short high-level explanation
http://gitimmersion.com/ for all of that, and more advanced concepts (also a longer tutorial)

**Comment by varjmes** [comment]
oh, and ~just~ can be removed :)

**Comment by rylev** [comment]
This definitely feels like it should be part of the appendix. We assume the reader is already at least somewhat proficient in higher level programming. It's not unreasonable to assume an understanding of version control and teaching version control has little to do with lower level programming or OS development. Of course, helping form good habits is a nice addition so including it in the appendix sounds like a reasonable option to me.

**Comment by steveklabnik** [comment]
I'm going to go with "just removed", I don't think we have enough interesting things to say here.

**Comment by dvberkel** [comment]
@steveklabnik I am still up for producing a little tutorial for git specific to intermezzOS if you want to say something about git at all. Or does "just removed" mean that git is completely of the table?

**Comment by steveklabnik** [comment]
If you think that there's enough interesting stuff about git stuff and intermezzOS specifically, then I'm open to including something in an appendix about it.

**Comment by dvberkel** [comment]
It would be vain to suppose that I could contribute anything new to existing git tutorials. The only thing that I could contribute is the knowledge which files to put under version control and which files to ignore and how to do that.

So I will not pursue this any further until a real need arises.

**Comment by varjmes** [comment]
> under version control and which files to ignore and how to do that.

that would be useful. i had to guess by looking at intermezzOS/kernel

**Comment by dvberkel** [comment]
If @Charlotteis  thinks this is useful I will write a short draft. I would have no hard feelings if this would not get accepted in the book. I will create a separate branch for this.

**Pull request merged**
