### PR TITLE
Change `bit selling point` to `big selling point`

### PR DESCRIPTION
**Pull request by dvberkel**
This is a small correction to virtual machine paragraph. While I was reading the book I found that `big` bas misspelled as `bit`.

Just my two cents for contributing to this awesome project.

### CODE REVIEW

**Comment by dvberkel** [comment]
Sorry, I messed up this pull request. It also incorporates the changes from pull-request #10. I am sorry. I will be more careful next time around.

**Comment by steveklabnik** [comment]
It's all good! This says it has a merge conflict though...

**Comment by dvberkel** [comment]
I will rebase in the evening

**Comment by dvberkel** [comment]
This pull request is closed. In its place is the cleaner pull request #12

**Pull request closed without merging**
