### PR TITLE
better pacman command

### PR DESCRIPTION
**Pull request by sullyj3**

### CODE REVIEW

**Comment by steveklabnik** [comment]
Interesting, what does this flag do?

**Comment by bjorn3** [comment]
--needed asks pacman to not reinstall packages if they are already installed. If i recall it correct.

**Comment by sullyj3** [comment]
More precisely, to not reinstall packages if they're already _up to date_.

**Comment by steveklabnik** [comment]
Cool. Thanks so much!

**Comment by sullyj3** [comment]
You're welcome!

**Pull request merged**
