### PR TITLE
Include a Troubleshooting chapter

### LINKED ISSUE #39: QEMU says no multiboot header found, load kernel first.
Hello, again.

I got as far as linking my boot.asm and multiboot_header.asm scripts. I had errors trying to turn my files into an .iso but I followed the fix here: https://github.com/intermezzOS/book/issues/35. Now when I try to load my ISO in QEMU I get:

```
error: no multiboot header found
error: you need to load the kernel first
```

As far as I can tell, my code is identical to yours in intermezzOS/kernel. You can see my code here: https://github.com/Charlotteis/charlotteOS

Here is the ouput of the `os.iso` creation, in case that is useful.

``` shell
charlotte@var-MacBookPro:~/projects/charlotteOS$ grub-mkrescue -o os.iso isofiles
xorriso 1.3.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:os.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 68.4g free
Added to ISO image: directory '/'='/tmp/grub.09DKxz'
xorriso : UPDATE : 548 files added in 1 seconds
Added to ISO image: directory '/'='/home/charlotte/projects/charlotteOS/isofiles'
xorriso : UPDATE : 552 files added in 1 seconds
xorriso : NOTE : Copying to System Area: 512 bytes from file '/usr/lib/grub/i386-pc/boot_hybrid.img'
xorriso : UPDATE :  100.00% done
ISO image produced: 5489 sectors
Written to medium : 5489 sectors at LBA 0
Writing to 'stdio:os.iso' completed successfully.
```

I am running a fresh install of Ubuntu 14 LTS on a 2012-ish Macbook Pro.

### LINKED ISSUE #45: grub-mkrescue fails with "Cannot find path 'efi.img' in loaded ISO image"
When building the .iso file, grub-mkrescue aborted with the error
`xorriso : FAILURE : Cannot find path '/efi.img' in loaded ISO image`

This from the command given in 3.3 Making an ISO.

### LINKED ISSUE #48: QEMU video doesn't work
In section 3.4, "Running in QEMU", when running 
`$ qemu-system-x86_64 -cdrom os.iso`
I get the following when executed over ssh or VM console:
`Could not initialize SDL(No available video device) - exiting`

Running `qemu-system-x86_64 -curses -cdrom os.iso` works. Though instructions on how to exit the emulator would be great too.

Debian Jessie on VirtualBox 5.0.0.

By the way, this is a great tutorial. Everything has been explained very well so far.

### PR DESCRIPTION
**Pull request by steveklabnik**
Fixes #39
Fixes #45
Fixes #48

### CODE REVIEW

**Comment by varjmes** [comment]
Looks great! :)

**Comment by rylev** [comment]
Can we mention in the main text that if the reader runs into issues they can find possible fixes here?

**Comment by steveklabnik** [comment]
Yes, that's a good call :+1:

**Comment by steveklabnik** [comment]
Upadated!

**Comment by rylev** [comment]
:heart_eyes: :+1:

**Pull request merged**
